# F2.DUV-035 · Proto-Nexus · fly.toml
# Configuración para despliegue en Fly.io bajo el plan gratuito de Cero Costo

app = "proto-nexus-soberano"

primary_region = "mia" # Miami - Región gratuita con buena latencia

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = true  # Ahorro de créditos, costo cero mientras no se use
  auto_start_machines = true # Reactivación bajo demanda
  min_machines_running = 0   # Garantiza el costo cero en inactividad

# Volumen persistente y gratuito (hasta 3GB en el plan free)
[mounts]
  source = "pb_data"
  destination = "/pb/pb_data"
