# DUV-040 • Proto-Nexus v2 • Render Blueprint
# Define un Web Service (Node.js) y una Base de Datos PostgreSQL, ambos en plan Free.

services:
  - type: web
    name: proto-nexus-web
    env: node
    plan: free
    autoDeploy: false # Despliegues manuales para máximo control
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      # DATABASE_URL se inyecta desde la BD Free definida abajo
      - key: DATABASE_URL
        fromDatabase:
          name: proto-nexus-db
          property: connectionString
    scaling:
      minInstances: 0 # Permite suspensión por inactividad para Cero Costo
      maxInstances: 1

databases:
  - name: proto-nexus-db
    plan: free
